"""estrutura inicial

Revision ID: 75dadfe6f5d8
Revises: 
Create Date: 2026-09-09 18:17:34.391542

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '75dadfe6f5d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_centros_custo',
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tb_centros_custo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tb_centros_custo_codigo'), ['codigo'], unique=True)

    op.create_table('tb_fornecedores',
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tb_fornecedores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tb_fornecedores_nome'), ['nome'], unique=True)

    op.create_table('tb_naturezas',
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tb_naturezas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tb_naturezas_nome'), ['nome'], unique=True)

    op.create_table('tb_usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('perfil', sa.String(length=20), server_default='leitor', nullable=False),
    sa.Column('ativo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ultimo_acesso', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("perfil IN ('leitor', 'operador', 'admin')", name='ck_usuario_perfil'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tb_usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tb_usuarios_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_tb_usuarios_external_id'), ['external_id'], unique=True)

    op.create_table('tb_auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('acao', sa.String(length=50), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('alvo_tipo', sa.String(length=50), nullable=False),
    sa.Column('alvo_id', sa.Integer(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['tb_usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tb_auditoria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tb_auditoria_acao'), ['acao'], unique=False)
        batch_op.create_index(batch_op.f('ix_tb_auditoria_alvo_id'), ['alvo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tb_auditoria_alvo_tipo'), ['alvo_tipo'], unique=False)
        batch_op.create_index(batch_op.f('ix_tb_auditoria_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_tb_auditoria_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('tb_importacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('arquivo', sa.String(length=255), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('linhas_lidas', sa.Integer(), server_default='0', nullable=False),
    sa.Column('linhas_ignoradas', sa.Integer(), server_default='0', nullable=False),
    sa.Column('criados', sa.Integer(), server_default='0', nullable=False),
    sa.Column('atualizados', sa.Integer(), server_default='0', nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['tb_usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tb_importacoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tb_importacoes_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_tb_importacoes_sha256'), ['sha256'], unique=False)

    op.create_table('tb_despesas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referencia', sa.Integer(), nullable=False),
    sa.Column('data_baixa', sa.Date(), nullable=False),
    sa.Column('data_emissao', sa.Date(), nullable=True),
    sa.Column('centro_custo_id', sa.Integer(), nullable=False),
    sa.Column('fornecedor_id', sa.Integer(), nullable=False),
    sa.Column('natureza_id', sa.Integer(), nullable=False),
    sa.Column('historico', sa.Text(), server_default='', nullable=False),
    sa.Column('documento', sa.String(length=30), server_default='', nullable=False),
    sa.Column('valor_original', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('valor_baixado', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('importacao_id', sa.Integer(), nullable=True),
    sa.Column('criado_por_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('valor_baixado IS NULL OR valor_baixado >= 0', name='ck_despesa_baixado'),
    sa.CheckConstraint('valor_original IS NULL OR valor_original >= 0', name='ck_despesa_original'),
    sa.ForeignKeyConstraint(['centro_custo_id'], ['tb_centros_custo.id'], ),
    sa.ForeignKeyConstraint(['criado_por_id'], ['tb_usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['tb_fornecedores.id'], ),
    sa.ForeignKeyConstraint(['importacao_id'], ['tb_importacoes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['natureza_id'], ['tb_naturezas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tb_despesas', schema=None) as batch_op:
        batch_op.create_index('ix_despesas_centro_natureza_data', ['centro_custo_id', 'natureza_id', 'data_baixa'], unique=False)
        batch_op.create_index('ix_despesas_periodo_centro', ['data_baixa', 'centro_custo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tb_despesas_centro_custo_id'), ['centro_custo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tb_despesas_data_baixa'), ['data_baixa'], unique=False)
        batch_op.create_index(batch_op.f('ix_tb_despesas_data_emissao'), ['data_emissao'], unique=False)
        batch_op.create_index(batch_op.f('ix_tb_despesas_documento'), ['documento'], unique=False)
        batch_op.create_index(batch_op.f('ix_tb_despesas_fornecedor_id'), ['fornecedor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tb_despesas_importacao_id'), ['importacao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tb_despesas_natureza_id'), ['natureza_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tb_despesas_referencia'), ['referencia'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_despesas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tb_despesas_referencia'))
        batch_op.drop_index(batch_op.f('ix_tb_despesas_natureza_id'))
        batch_op.drop_index(batch_op.f('ix_tb_despesas_importacao_id'))
        batch_op.drop_index(batch_op.f('ix_tb_despesas_fornecedor_id'))
        batch_op.drop_index(batch_op.f('ix_tb_despesas_documento'))
        batch_op.drop_index(batch_op.f('ix_tb_despesas_data_emissao'))
        batch_op.drop_index(batch_op.f('ix_tb_despesas_data_baixa'))
        batch_op.drop_index(batch_op.f('ix_tb_despesas_centro_custo_id'))
        batch_op.drop_index('ix_despesas_periodo_centro')
        batch_op.drop_index('ix_despesas_centro_natureza_data')

    op.drop_table('tb_despesas')
    with op.batch_alter_table('tb_importacoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tb_importacoes_sha256'))
        batch_op.drop_index(batch_op.f('ix_tb_importacoes_criado_em'))

    op.drop_table('tb_importacoes')
    with op.batch_alter_table('tb_auditoria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tb_auditoria_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_tb_auditoria_criado_em'))
        batch_op.drop_index(batch_op.f('ix_tb_auditoria_alvo_tipo'))
        batch_op.drop_index(batch_op.f('ix_tb_auditoria_alvo_id'))
        batch_op.drop_index(batch_op.f('ix_tb_auditoria_acao'))

    op.drop_table('tb_auditoria')
    with op.batch_alter_table('tb_usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tb_usuarios_external_id'))
        batch_op.drop_index(batch_op.f('ix_tb_usuarios_email'))

    op.drop_table('tb_usuarios')
    with op.batch_alter_table('tb_naturezas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tb_naturezas_nome'))

    op.drop_table('tb_naturezas')
    with op.batch_alter_table('tb_fornecedores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tb_fornecedores_nome'))

    op.drop_table('tb_fornecedores')
    with op.batch_alter_table('tb_centros_custo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tb_centros_custo_codigo'))

    op.drop_table('tb_centros_custo')
    # ### end Alembic commands ###
